todoapp/urls.py
from django.urls import path
from . import views
app_name = 'todoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('todo/', views.todoappView, name='todo'),
    path('addTodoItem/',views.addTodoView), 
    path('deleteTodoItem/<int:id>/', views.deleteTodoView), 
    path('editTodoItem/<int:id>/', views.editTodoView, name='edit_todo_item'),

] 

todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls',)),
]

todoapp/models.py
from django.db import models


# Create your models here.
class TodoListItem(models.Model):
    content = models.TextField() 

todoapp/views.py
from django.shortcuts import render
from .models import TodoListItem 
from django.http import HttpResponseRedirect 
# Create your views here.
def index(request):
    return render(request, 'index.html')



def todoappView(request):
    all_todo_items = TodoListItem.objects.all()
    return render(request, 'todolist.html',  {'all_items':all_todo_items})


def addTodoView(request):
    new_item = TodoListItem()
    new_item.content = request.POST.get('content')
    new_item.save()
    return HttpResponseRedirect('/todo/') 


def deleteTodoView(request, id):
    y = TodoListItem.objects.get(id= id)
    y.delete()
    return HttpResponseRedirect('/todo/') 


def editTodoView(request,id):
    todo_item = TodoListItem.objects.get(id=id)
    if request.method == 'POST':
        todo_item.content = request.POST.get('content')
        todo_item.save()
        return HttpResponseRedirect('/todo/') 
    elif request.method == 'GET':
        return render(request, 'todolist.html', {'todo_item': todo_item})

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
    
<div class="container">
    <div class="card text-center" style="margin-top: 200px;">
        <div class="card-header">
          Dev By Mangesh Mahadeo Kokare 22112035
        </div>
        <div class="card-body">
          <h5 class="card-title">Welcome to the app</h5>
          <p class="card-text">Make life easier by creating ToDo List</p>
          <a href="{% url 'todoapp:todo' %}" class="btn btn-primary">Start Now!</a>
        </div>
        <div class="card-footer text-muted">
          2 days ago
        </div>
      </div>
</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>

templates/todolist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
    
<div class="container">
<!-- 
    <div class="row">
        <form action="/addTodoItem/" method = "post">
            {% csrf_token %}
            <input type="text" name="content">
            <input type="submit" value="Add Todo Item">
        </form> 
    </div>

    <div class="row">
        <ul>
            {% for i in all_items %} 
            <li>{{i.content}}
            </li>
            <form action="/deleteTodoItem/{{i.id}}/" method = "post">{% csrf_token %}
                <input type="submit" value="Delete">
    </form> 
            {% endfor %}
        </ul> 
    </div>
 -->

    <div class="row" style="margin-top: 20px;">
        <div class="col">
            <div class="row">
                <form class="form-inline" action="/addTodoItem/" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-8">
                            <div class="form-group mx-sm-3 mb-2">
                                <label for="content" class="sr-only"></label>
                                <input type="text" class="form-control" name="content" placeholder="Research">
                            </div>
                        </div>
                        <div class="col-4" style="margin-top: 25px;">
                            <button type="submit" class="btn btn-primary mb-2">Add Todo</button>
                        </div>
                    </div>
                </form>
            </div>
            {% for i in all_items %}
            <div class="row">
                <div class="col-6">
                    <div class="card text-white bg-dark mb-3">
                        <div class="card-body">
                            {{ i.content }}
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <!-- Edit button -->
                    <form action="/editTodoItem/{{ i.id }}/" method="get">
                        <button type="submit" class="btn btn-info">
                            Edit
                        </button>
                    </form>
                    <!-- Delete button -->
                    <form action="/deleteTodoItem/{{ i.id }}/" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">
                            Delete
                        </button>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    


</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>